//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CR31.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public string FIO { get; set; }
        public string BrandCar { get; set; }
        public string Model { get; set; }
        public string LeaseTime { get; set; }
    }
}
