//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CR31.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tax
    {
        public int TaxID { get; set; }
        public int ContractID { get; set; }
        public int ClientID { get; set; }
        public int ExployeeID { get; set; }
        public int CarID { get; set; }
        public decimal Amount_tax { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Contract Contract { get; set; }
    }
}
